<a href="https://colab.research.google.com/github/ImNotDanish05/2025_KC_TI-1A/blob/main/Jobsheet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Tipe Data Python Integer
# By: ImNotDanish05
var = 123
print(type(var))

<class 'int'>


In [4]:
# By: ImNotDanish05
# Tipe data string
hmm = "Maaoww"
print(type(hmm))

<class 'str'>


In [5]:
# By: ImNotDanish05
# Tipe data numerik
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))
print(f1)

sum_result = var1 + var2
print(sum_result)

var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)

print(i1)
print(i2)


<class 'float'>
345.0
379.5
34
12


In [7]:
# By: ImNotDanish05
var1 = 345
var2 = 34.5
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

False
False
True
True


In [8]:
# By: ImNotDanish05
my_list = ["belajar dasar python", 2023, 3.8, True]
print(my_list)

print(my_list[3])
print(my_list[1:3])
print(len(my_list))


['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


In [62]:
# By: ImNotDanish05
# Nilai Minimum dan Maximum
x = min(5, 10, 25)
y = max(6, 12, 18)

print(x, y)


5 18


In [11]:
# By: ImNotDanish05
# Mendapatkan nilai absolut
x = abs(-7.25)
print(x)

7.25


In [12]:
# By: ImNotDanish05
# Mendapatkan nilai pangkat
import math
x = math.pow(4, 3)
print(x)


64.0


In [14]:
# By: ImNotDanish05
# Mendapatkan nilai akar
import math
x = math.sqrt(64)
print(x)

8.0


In [15]:
# By: ImNotDanish05
# Mendapatkan nilai pembulatan
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x, " and ", y)

2  and  1


In [16]:
# By: ImNotDanish05
# nilai konstanta (PI)
import math
x = math.pi
print(x)

3.141592653589793


In [26]:
# By: ImNotDanish05
#
import math

# 1. math.sin() -> Menghitung sinus dari sudut (dalam radian)
sin_value = math.sin(math.radians(30))  # Konversi 30 derajat ke radian sebelum dihitung
print(sin_value)

0.49999999999999994


In [27]:
# By: ImNotDanish05
#
import math
# 2. math.cos() -> Menghitung cosinus dari sudut (dalam radian)
cos_value = math.cos(math.radians(60))
cos_value

0.5000000000000001

In [28]:
# By: ImNotDanish05
#
import math
# 3. math.tan() -> Menghitung tangen dari sudut (dalam radian)
tan_value = math.tan(math.radians(45))
tan_value


0.9999999999999999

In [29]:
# By: ImNotDanish05
#
import math
# 4. math.log() -> Menghitung logaritma natural (basis e)
log_value = math.log(10)
log_value

2.302585092994046

In [30]:
# By: ImNotDanish05
#
import math
# 5. math.log10() -> Menghitung logaritma basis 10
log10_value = math.log10(100)
log10_value


2.0

In [31]:
# By: ImNotDanish05
#
import math
# 6. math.degrees() -> Mengubah sudut dari radian ke derajat
degrees_value = math.degrees(math.pi / 2)
degrees_value

90.0

In [32]:
# By: ImNotDanish05
#
import math
# 7. math.dist() -> Menghitung jarak Euclidean antara dua titik dalam ruang n-dimensi
dist_value = math.dist([1, 2], [4, 6])
dist_value

5.0

In [33]:
# By: ImNotDanish05
#
import math
# 8. math.factorial() -> Menghitung faktorial dari suatu bilangan bulat non-negatif
factorial_value = math.factorial(5)
factorial_value

120

In [34]:
# By: ImNotDanish05
#
import math
# 9. math.fmod() -> Menghitung sisa hasil pembagian (modulus) dengan presisi floating-point
fmod_value = math.fmod(10.5, 3)
fmod_value

1.5

In [35]:
# By: ImNotDanish05
#
import math

# 10. math.isnan() -> Mengecek apakah suatu nilai adalah NaN (Not a Number)
nan_value = math.isnan(float('nan'))
nan_value

True

In [36]:
# By: ImNotDanish05
#
import math
# 11. math.gamma() -> Menghitung fungsi gamma dari suatu bilangan
gamma_value = math.gamma(5)
gamma_value

24.0

In [37]:
# By: ImNotDanish05
#
import math

# 12. math.perm() -> Menghitung permutasi dari dua bilangan (nPr)
perm_value = math.perm(5, 2)
perm_value

20

In [39]:
# By: ImNotDanish05
# Pastikan sudah running semua program diatas untuk ini bekerja :V
(
    sin_value, cos_value, tan_value, log_value, log10_value,
    degrees_value, dist_value, factorial_value, fmod_value,
    nan_value, gamma_value, perm_value
)

(0.49999999999999994,
 0.5000000000000001,
 0.9999999999999999,
 2.302585092994046,
 2.0,
 90.0,
 5.0,
 120,
 1.5,
 True,
 24.0,
 20)

In [41]:
# By: ImNotDanish05
#
import numpy as np
A = np.array([[80, 30, 25],
[50, 20, 10]])
B = np.array([[30, 60, 15],
[10, 30, 30]])

hasil = A + B
hasil

array([[110,  90,  40],
       [ 60,  50,  40]])

In [43]:
# By: ImNotDanish05
#
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
hasil

np.int64(2025)

In [46]:
# By: ImNotDanish05
#
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)
Hasil

array([-305, -110,  350])

In [52]:
# By: ImNotDanish05
#
import numpy as np

A = np.array([[3, 1], [2,0]])
B = np.array([[2,1],[1,-1]])
C = np.array([[-1,1,2],[2,0,1]])

hasil1 = A @ B
hasil2 = B @ C
hasil3 = A * B #Testing aja :V

print("Hasil Jawaban A: ", hasil1)
print(f"Hasil Jawaban B: {hasil2}")
print(f"Hasil Ketiga: {hasil3}")

Hasil Jawaban A:  [[7 2]
 [4 2]]
Hasil Jawaban B: [[ 0  2  5]
 [-3  1  1]]
Hasil Ketiga: [[6 1]
 [2 0]]


In [59]:
# By: ImNotDanish05
# Nomor 2 Faktorial
import math as m

# SOAL
# 2.	Hitunglah nilai dari soal faktorial berikut
# a.	6!
f6 = m.factorial(6)
print(f'Jawaban nomor A adalah "{f6}"')

# b.	8! / 5!
f8 = m.factorial(8)
f5 = m.factorial(5)

hasil = f8 / f5
print(f'Jawaban nomor B adalah "{hasil}"')

Jawaban nomor A adalah "720"
Jawaban nomor B adalah "336.0"


In [61]:
# By: ImNotDanish05
# Nomor 3
import numpy as np

# 3.	Dua Buah Vektor A dan B merupakan vektor 3D pada koordinat kartesian.
# Jika Vektor A = 5i + 3j + 7k dan Vektor B = 12i – 3j + k.
# Maka tentukan panjang masing-masing Vektor, hasil perkalian titik A.B, dan AxB.

vectorA = np.array([5, 3, 7])
vectorB = np.array([12, -3, 1])

# Panjang vektor A dan B
panjang_A = np.linalg.norm(vectorA)
panjang_B = np.linalg.norm(vectorB)

# 2. Perkalian Titik (Dot Product)
dot_product = np.dot(vectorA, vectorB)

# 3. Perkalian Silang (Cross Product)
cross_product = np.cross(vectorA, vectorB)

print("Panjang Vektor A =", panjang_A)
print("Panjang Vektor B =", panjang_B)
print("A . B =", dot_product)
print("A x B =", cross_product)


Panjang Vektor A = 9.1104335791443
Panjang Vektor B = 12.409673645990857
A . B = 58
A x B = [ 24  79 -51]
